---
kind: pipeline
type: docker
name: default

steps:
- name: test
  image: python:3-alpine
  commands:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - ls -latr
  - pytest
  - ls -latr

- name: coveralls
  image: lizheming/drone-coveralls
  settings:
    token:
      from_secret: coveralls_token
    files:
    # TODO: find out which file(s) are generated & need sending to coveralls:
    - ./lcov.info

- name: pypi-publish
  image: plugins/pypi
  settings:
    username:
      from_secret: public_pypi_username
    password:
      from_secret: public_pypi_password
  when:
    event:
    - tag

trigger:
  ref:
  - refs/heads/master
  - refs/heads/develop
  - refs/heads/feature/*
  - refs/tags/*
